Actividad 1: Identificacion de la fuente

1.- Quien produjo originalmente los datos? <br>
UN, World Population Prospects (2024)<br>

2.- Que organizacion los procesa para su utilizacion?<br>
Our World In Data<br>

3.- ¿Qué representa la variable que analizarás? <br>
El crecimiento anual de la poblacion

Actividad 2 — Carga y exploración de datos

1.- ¿Cuántas filas y columnas tiene el dataset? (.shape) <br>
tiene 38400 filas y 5)

2.- ¿Qué tipo de datos contiene la variable Year? <br>
tiene int

3.- ¿Existen valores faltantes? (.isnull().sum()) <br>
En Entity y Year no, en los otros 3 si

4.- ¿Cuántas entidades diferentes contiene el dataset? (["Entity"].unique()) <br>
Son 256 entities unicas

In [2]:
import pandas as pd 
import numpy as np

dataframe = pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [3]:
#dataframe.head(3)
#dataframe.tail()
dataframe.isnull().sum()
#dataframe.shape

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [4]:
dt_Entities = dataframe[["Entity","Year"]]
dt_Entities.head(3)
#dt_Entities.shape

        Entity  Year
0  Afghanistan  1951
1  Afghanistan  1952
2  Afghanistan  1953

In [5]:
df_2020 = dataframe[dataframe["Year"] == 2020]#filtra las filas, se trae todo pero solo filtra la Serie "Year"
df_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN

In [6]:
#df_columnas_2020_independiente = dataframe[dataframe["Year"] == 2020][["Entity","Year"]]
#filtra las filas primero y despues las columnas df[df[]] [["",""]]
df_columnas_2020 = df_2020[["Entity","Year"]]
df_columnas_2020.head(3)

          Entity  Year
69   Afghanistan  2020
219  Africa (UN)  2020
369      Albania  2020

In [7]:
df_2005_2020 = dataframe[(dataframe["Year"] >= 2005) & (dataframe["Year"] <= 2020) &
                          (dataframe["Entity"] == "Mexico")]
df_2005_2020.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22254,Mexico,MEX,2005,1417373.0,NaN
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN
22258,Mexico,MEX,2009,1625434.0,NaN

In [8]:
df_2005_2020_Entity_Annual = df_2005_2020[["Entity","Annual change in population"]]
df_2005_2020_Entity_Annual.head()

       Entity  Annual change in population
22254  Mexico                    1417373.0
22255  Mexico                    1442162.0
22256  Mexico                    1520690.0
22257  Mexico                    1599930.0
22258  Mexico                    1625434.0

In [9]:
df_2005_2020_Entity_Annual.mean(numeric_only=True) #la media

Annual change in population    1400307.625
dtype: float64

In [10]:
dataframe["Entity"].unique()

<StringArray>
[        'Afghanistan',         'Africa (UN)',             'Albania',
             'Algeria',      'American Samoa',       'Americas (UN)',
             'Andorra',              'Angola',            'Anguilla',
 'Antigua and Barbuda',
 ...
             'Vanuatu',             'Vatican',           'Venezuela',
             'Vietnam',   'Wallis and Futuna',      'Western Sahara',
               'World',               'Yemen',              'Zambia',
            'Zimbabwe']
Length: 256, dtype: str

Actividad 3 — Estadística descriptiva

In [11]:
#1. estadisticos, España 1983-2021, media-etc

In [ ]:
df_1 = dataframe[(dataframe["Entity"] == "Spain") & (dataframe["Year"] >= 1983) &
                  (dataframe["Year"] <= 2021)][["Entity","Year","Annual change in population"]]
#df_1.mean()
#df.mean() 
#df.median() 
#df.var() 
#df.std() 
#df.min() 
#df.max()

In [ ]:
#2. dataframe original, pais con el minimos y el del maximo, poblacion annual
df_2 = dataframe[(dataframe["Entity"] != "World") & (dataframe["Entity"] != "Less developed regions") &
                 (dataframe["Entity"] != "Less developed regions, excluding China") &
                 (dataframe["Entity"] != "Less developed regions, excluding least developed countries") &
                 (dataframe["Entity"] != "Asia (UN)") & (dataframe["Entity"] != "Lower-middle-income countries") &
                 (dataframe["Entity"] != "Upper-middle-income countries") & (dataframe["Entity"] != "Africa (UN)")
                 & (dataframe["Entity"] != "Least developed countries")
                 ]

df_num2 = df_2[(df_2["Annual change in population"] == df_2["Annual change in population"].min()) |
                     (df_2["Annual change in population"] == df_2["Annual change in population"].max())
                     ][["Entity","Annual change in population"]]
df_num2

        Entity  Annual change in population
6769     China                   21168623.0
35772  Ukraine                   -3315935.0

Actividad 4 — Comprobación del entorno

In [ ]:
#dataframe.loc[600:610,["Entity","Code"]] #extraccion de fila primero, columna despues//: = todas las cosas de ahi (todas las filas)
dataframe.iloc[600:610,0:3] #0:3 es un rango//Posicion iloc, valor loc

             Entity Code  Year
600  American Samoa  ASM  1951
601  American Samoa  ASM  1952
602  American Samoa  ASM  1953
603  American Samoa  ASM  1954
604  American Samoa  ASM  1955
605  American Samoa  ASM  1956
606  American Samoa  ASM  1957
607  American Samoa  ASM  1958
608  American Samoa  ASM  1959
609  American Samoa  ASM  1960

In [ ]:
#dataframe.loc[:,["Entity","Year","Annual change in population"]]
dataframe.iloc[:,[0,2,3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [ ]:
#dataframe.loc[10000],["Entity","Year","Annual change in population"]
#dataframe.iloc[1000,[0,2,3]]
#test = dataframe[(dataframe["Entity"] == "Mexico") & (dataframe["Year"] == 2020)
#                 ][["Entity","Year","Annual change in population"]]
dataframe.loc[(dataframe["Entity"] == "Mexico") & (dataframe["Year"] == 2020),
              ["Entity","Year","Annual change in population"]]

       Entity  Year  Annual change in population
22269  Mexico  2020                    1036075.0